### ISSUE TITLE
Create a bot for Meterian in GitHub in order to push PR

### ISSUE THREAD

**Issue by bbossola** [MeterianHQ/jenkins-plugin#10]

**Comment by bbossola** [comment]
@meterian-bot created!

**Comment by neomatrix369** [comment]
Thanks @bbossola do I need a new OAuth token?

**Comment by neomatrix369** [comment]
Need email address for the bot, already messaged you elsewhere about it, whenever you have it ping it to me

**Comment by neomatrix369** [comment]
@bbossola There are a couple of edge-cases to think about, lets discuss when we can next
