### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by neomatrix369** [MeterianHQ/jenkins-plugin#24]
After the meterian client finishes analysing a project, among many log messages we see:

```bash
...
[meterian] Build unsuccesful!
...
```

Correction: unsuccesful => unsuccessful

Note: The correction would need to be made at the meterian client end, not a change for the jenkins plugin.

**Comment by neomatrix369** [comment]
@bbossola any updates for this?

**Comment by bbossola** [comment]
It's fiixed but it did not get published to canary... I need to check my buiild script, I will come back to you

**Comment by bbossola** [comment]
Canary fixed, should work now.

**Comment by neomatrix369** [comment]
Fixed I think! Caused my PR to break but now its resolved.
