### ISSUE TITLE
[Question] Re-running meterian client on a fixed project still shows "Build unsuccesful!"?

### ISSUE THREAD

**Issue by neomatrix369** [MeterianHQ/jenkins-plugin#25]
After running the meterian client on a project with the `--autofix` flag - which applies the fix and commits the changes, if the meterian client is re-run on the project the new results are still "Build unsuccesful!".

There could be a step that cannpt be autofixed, like adding a license to the project or some other manual step.

Does this mean we still break the build - this could lead to a cyclic-loop? What's the best action to take here.

This is returning a non-zero exit code which is resulting in the `--autofix` tests to fail despite applying the fix the first time over - potential bug.

**Comment by neomatrix369** [comment]
Here is a typical false positive failure result:

```
[snipped]
[meterian] Starting build...
[meterian] Current build status: in preparation
[meterian] Current build status: process advices at 2019-06-05T13:52:54.389
[meterian] 
[meterian] Autofix requested - current scores:
[meterian] - security:	35	(minimum: 90)
[meterian] - stability:	100	(minimum: 80)
[meterian] - licensing:	99	(minimum: 95)
[meterian] 
[meterian] 
[meterian] Running autofix, 1 programs
[meterian] (program 1)
[meterian] - reach:     will update all versions (all)
[meterian] - strategy:  will update with patch releases (safe)
[meterian] - override:  will override packages
[meterian] - variables: will not touch variables
[meterian] 
[meterian] Sorry, no changes made. Try a different reach or strategy!
[meterian] 
[meterian] 
[meterian] Final results: 
[meterian] - security:	35	(minimum: 90)
[meterian] - stability:	100	(minimum: 80)
[meterian] - licensing:	99	(minimum: 95)
[meterian] 
[meterian] Full report available at: 
[meterian] https://www.meterian.com/projects.html?pid=e62467fb-7d04-4c26-b32e-9997a857d3fb&branch=1.0-SNAPSHOT&mode=eli
[meterian] 
[meterian] Build unsuccesful!
[meterian] Failed checks: [security]
[meterian] 
No changes found (no fixes generated), no branch to push to the remote repo.
[meterian] Warning: fixed-by-meterian-29c4d26 already exists in the remote repo, skipping the remote branch creation process.
[meterian] Warning: Found 1 pull request(s) for org: MeterianHQ, repo: MeterianHQ/autofix-sample-maven-upgrade, branch: fixed-by-meterian-29c4d26
[meterian] Warning: Pull request already exists for this branch, no new pull request will be created. Fixed already generated for current branch (commit point).
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: FAILURE
```

As you can see from the above, there is no fix to be applied from the point of view of `--autofix` and we have a PR already waiting to be merged but the build breaks as the Meterian Client runner returns `1` as exit code.

I have run this under all scenarios:
- without autofix (on an unfixed branch), returns exit code `1` 
- with autofix (on an unfixed branch), returns exit code `1`
- with autofix on an already fixed branch, returns exit code `1`

**Comment by neomatrix369** [comment]
For the test case to pass we need a scenario where the security is fixed and does not fail due to security. We didn't have this issue sometime back, it must be a recent change.

Should we choose a different repo to perform our tests?

**Comment by bbossola** [comment]
> After running the meterian client on a project with the --autofix flag - which applies the fix and commits the changes, if the meterian client is re-run on the project the new results are still "Build unsuccesful!".

The client will fix as much as he can with the currently selected strategy, which, by default, is quite conservative. If the fixes do not bring the scores high enough to pass the thresholds, then the client will exit with failure.  Of course _some_ changes are made. Do we want to commit them and create a PR in that situation? Probably not. In that case we should fail the build.

**Comment by bbossola** [comment]
> For the test case to pass we need a scenario where the security is fixed and does not fail due to security. We didn't have this issue sometime back, it must be a recent change.
> Should we choose a different repo to perform our tests?

That's the infortunate case of vulnerabilities, that pop up all the time. I guess that's a jackson-databind one? Very popular :) I will have a look and see if I can produce a more consistent project with a single simple patch.

**Comment by neomatrix369** [comment]
> > For the test case to pass we need a scenario where the security is fixed and does not fail due to security. We didn't have this issue sometime back, it must be a recent change.
> > Should we choose a different repo to perform our tests?
> 
> That's the infortunate case of vulnerabilities, that pop up all the time. I guess that's a jackson-databind one? Very popular :) I will have a look and see if I can produce a more consistent project with a single simple patch.
> 
> [EDIT]
> Ok done, now it should be back on, autofix should work as expected. As I suspected, there's no way out if you are using jackson-databind 2.8.11.3: this might as well happen in real life

Thanks for confirming this, it's also a good use case to have, these corner cases are good to come across during development phase.

Can you if possible provide me a project with vulnerabilities, which gets fixed completely with `--autofix` so we can use it for our happy-path tests cases.

**Comment by neomatrix369** [comment]
> > After running the meterian client on a project with the --autofix flag - which applies the fix and commits the changes, if the meterian client is re-run on the project the new results are still "Build unsuccesful!".
> 
> The client will fix as much as he can with the currently selected strategy, which, by default, is quite conservative. If the fixes do not bring the scores high enough to pass the thresholds, then the client will exit with failure. Of course _some_ changes are made. Do we want to commit them and create a PR in that situation? Probably not. In that case we should fail the build.

That's good to know although, it would help if there was some indication in the form of a console message or even an exit code (error code) that indicates that we haven't been able to fix this fully.

I see 3 scenarios among others:

- run without autofix, reports project has vulnerabilities, exits with **non-zero error code**
- run with autofix, reports project has vulnerabilities, fixes partially, exits with **non-zero error code**
- run with autofix, reports project has vulnerabilities, fixes fully, exits with **zero error code**

**Comment by bbossola** [comment]
The client behavior in terms of exit code is already programmed. It exits with 0 if the analysis is successful and with a nonzero exit code (which stops i.e. Jenkins) on analysis failure. So the general behaviour should be to fail the build if a nonzero code is returned. As described [in the manual](https://www.meterian.com/documents/meterian-cli-manual.pdf):

_"...In case of error the code will be calculated using a bitmask over the exit code: +1 for a fail
on the security score, +2 for a fail on the stability score, +4 for a fail on the licensing score. "_

I think that your scenarios are already captured from the current exit code. Basically the client exits with zero, regardless of autofix or not, only if the scores are over/equal to the tresholds.

**Comment by neomatrix369** [comment]
Closing issue but will open a new one to request for a project that is fixe 100% with `--autofix`
