### ISSUE TITLE
Questions about action to take when meterian client has been re-run

### ISSUE THREAD

**Issue by neomatrix369** [MeterianHQ/jenkins-plugin#27]
Meterian client is re-run on:

- master or a branch which has a local and remote branch and a pending PR
  - should the build break or finish successfully? Break because PR is not yet merged?
- a fixed branch (created by Meterian) which is pushed to remote and linked to a pending PR 
  - should the build finish successfully? Since a PR is waiting to be merged.

**Comment by neomatrix369** [comment]
Any update for this one @bbossola, these are a couple of corner cases to think about

**Comment by bbossola** [comment]
Both cases if the client returns a nonzero exit code then fails, otherwise success BUT it should not create a PR over a meterian created branch.

**Comment by bbossola** [comment]
Shall we close this?

**Comment by neomatrix369** [comment]
> Shall we close this?

Yes
