### ISSUE TITLE
New maven project that can be fully fixed by --autofix

### ISSUE THREAD

**Issue by neomatrix369** [MeterianHQ/jenkins-plugin#28]
On the back of the answer to the question on #25, can I please request a maven project that can be fully fixed by `--autofix`.

We need this to patch the tests written via the PR #18 #19 and #20 

Please add my GitHub user to this project as a collaborator.

**Comment by bbossola** [comment]
I forgot to push, the MeterianHQ/autofix-sample-maven-upgrade.git is fully autofixable now (unless until a new vuln come up :))
